export ZSH=$HOME"/.oh-my-zsh"

plugins=(git kubectl)

POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator kubecontext command_execution_time)

TERMINAL_BACKGROUND=236
RED=009
GREEN=010
YELLOW=011
BLUE=012

# Set 'dir' segment colors
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=$TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_HOME_FOREGROUND=$TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=$TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_ETC_FOREGROUND=$TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=$BLUE
POWERLEVEL9K_DIR_HOME_BACKGROUND=$BLUE
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=$BLUE
POWERLEVEL9K_DIR_ETC_BACKGROUND=$BLUE

# Set 'os_icon prompt' parameters
POWERLEVEL9K_OS_ICON_BACKGROUND=067
POWERLEVEL9K_OS_ICON_FOREGROUND=000

# Set 'command_execution_time prompt' parameters
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=037
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=000

# Set 'kubecontext prompt' parameters
POWERLEVEL9K_KUBECONTEXT_BACKGROUND=240
POWERLEVEL9K_KUBECONTEXT_FOREGROUND=015

PATH="$PATH:$HOME/go/bin"
source $HOME/.zsh_aliases
source $HOME/.profile
source $ZSH/oh-my-zsh.sh
